CREATE TABLE `Account_Balance` (
	`account_id` VARCHAR(10) NOT NULL,
	`sub_account_id` VARCHAR(10) NOT NULL,
	`group_id` VARCHAR(10) NOT NULL,
	`organization_id` VARCHAR(10) NOT NULL,
	`resource_person_id` VARCHAR(10) NOT NULL,
	`cow_cast_id` VARCHAR(10) NOT NULL,
	`issue_date` DATE,
	`birth_date` DATE,
	`birth_wt` DECIMAL,
	`join_date` DATE,
	`join_wt` DECIMAL,
	`heifer_date` DATE,
	`calwing_date` DATE,
	`cancel_date` DATE,
	`death_date` DATE,
	`op_balance` DECIMAL NOT NULL,
	`op_crdr` CHAR(2) NOT NULL,
	`cr_amount` DECIMAL,
	`dr_amount` DECIMAL,
	`cl_balance` DECIMAL,
	`cl_crdr` CHAR(2) NOT NULL,
	`insurance_date` DATE,
	`insurance_due_on` DATE,
	`insurance_tag_no` VARCHAR(25),
	`insurance_amount` DECIMAL,
	`insurance_remark` VARCHAR(50),
	PRIMARY KEY (`account_id`,`sub_account_id`)
);